"""Initial Migration

Revision ID: 919af2701332
Revises: 915f8fd4c68c
Create Date: 2020-12-17 14:54:16.971573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919af2701332'
down_revision = '915f8fd4c68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_title', sa.String(), nullable=True),
    sa.Column('article_body', sa.String(), nullable=True),
    sa.Column('article_tag', sa.String(), nullable=True),
    sa.Column('article_cover_path', sa.String(), nullable=True),
    sa.Column('article_comments_count', sa.Integer(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('article_upvotes', sa.Integer(), nullable=True),
    sa.Column('article_downvotes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
